-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3307
-- Generation Time: Jun 12, 2026 at 10:36 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `jutarnji`
--

-- --------------------------------------------------------

--
-- Table structure for table `korisnik`
--

CREATE TABLE `korisnik` (
  `id` int(11) NOT NULL,
  `ime` varchar(32) NOT NULL,
  `prezime` varchar(32) NOT NULL,
  `korisnicko_ime` varchar(32) NOT NULL,
  `lozinka` varchar(255) NOT NULL,
  `razina` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;

--
-- Dumping data for table `korisnik`
--

INSERT INTO `korisnik` (`id`, `ime`, `prezime`, `korisnicko_ime`, `lozinka`, `razina`) VALUES
(1, 'Leon', 'Kancir', 'kanc', '$2y$10$/9M3nums6C7znNT7lly22erF82GVE2Ueyy2Ysea7KROS1XSagC.8W', 1);

-- --------------------------------------------------------

--
-- Table structure for table `vijesti`
--

CREATE TABLE `vijesti` (
  `id` int(11) NOT NULL,
  `datum` varchar(32) NOT NULL,
  `naslov` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `sazetak` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `tekst` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `slika` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `kategorija` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `arhiva` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;

--
-- Dumping data for table `vijesti`
--

INSERT INTO `vijesti` (`id`, `datum`, `naslov`, `sazetak`, `tekst`, `slika`, `kategorija`, `arhiva`) VALUES
(8, '2026-06-12', '80 km/h, PMA, chômage, européennes... Ce qu\'il faut retenir de l', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak5.jpg', 'elections', 0),
(9, '2026-06-12', '\"Nous avons une capacité ? nous adresser ? des Français qui vien', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier Polyvalent la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak4.jpg', 'elections', 0),
(10, '2026-06-12', 'Italie: Matteo Salvini affaibli pour les européennes', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte cotton la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak3.jpg', 'elections', 0),
(11, '2026-06-12', 'INFO FRANCEINFO. Européennes : les Républicains et le RN n\'ont p', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak2.jpg', 'elections', 0),
(12, '2026-06-12', '\"Je vis sur la route, mais sans concert au bout\" on a passé une ', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak1.jpg', 'elections', 0),
(13, '2026-06-12', 'JT de 20h du jeudi 16 mai 2019', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak9.jpg', 'lesjt', 0),
(14, '2026-06-12', 'Grand Soir 3 du jeudi 16 mai 2019', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak8.jpg', 'lesjt', 0),
(15, '2026-06-12', 'Le JT de 7h de franceinfo du vendredi 17 mai 2019', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak7.jpg', 'lesjt', 0),
(16, '2026-06-12', 'JT de 8h du vendredi 17 mai 2019', '149 candidats français d\'autres partis l\'ont signé', 'Dans le cadre des élections européennes, l\'ONG Transparency International, qui lutte contre la corruption, a invité tous les candidats ? signer un plaidoyer afin qu\'ils s\'engagent ? protéger l\'État de droit, ? lutter contre l\'évasion fiscale et ? améliorer la transparence des institutions européennes.\r\n\r\nSuite ? un premier bilan effectué par l\'ONG, pour le moment, 149 candidats aux élections européennes en France ont signé ce plaidoyer, rév?le franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept t?tes de liste aux européennes (La France insoumise, Renaissance, Parti communiste, Europe Écologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Républicains n\'a signé. Or, ces deux listes regroupent ? elles seules 40% des candidats en position éligible.\r\n\r\n\"Encore des gens ? convaincre\"\r\nDans sa réponse ? l\'ONG, Jordan Bardella, t?te de liste RN, exprime des \"désaccords de fond\" avec les propositions de l\'ONG. La liste Les Républicains, elle aussi non signataire du plaidoyer, parle néanmoins d\'un soutien de principe ? la déontologie et ? l\'État de droit. Ce sont \"des partis qui n\'ont pas toujours été engagés sur ces questions\" affirme sur franceinfo Marc-André Feffer, le président de l\'ONG Transparency International. \"Et ce, soit pour des raisons liées ? l\'Union européenne, soit liées au souhait de privilégier finalement la déontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'? moitié plein\" estime Marc-André Feffer. Sur les 2 686 candidats aux européennes, 149 ont signé le plaidoyer. \"Ceux qui ont répondu positivement nous aident beaucoup. Il y a encore des gens ? convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-l?.\"\r\n\r\nCourant mai, l\'ONG Transparency International a réalisé un sondage aupr?s de la population qui rév?le que 88% des Français jugent prioritaire le renforcement de l\'éthique et de la transparence dans les institutions européennes.', 'fotoclanak6.jpg', 'lesjt', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `korisnik`
--
ALTER TABLE `korisnik`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `korisnicko_ime` (`korisnicko_ime`);

--
-- Indexes for table `vijesti`
--
ALTER TABLE `vijesti`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `korisnik`
--
ALTER TABLE `korisnik`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `vijesti`
--
ALTER TABLE `vijesti`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
